name: napalm-registry
license: MIT

dependencies:
    - aeson
    - base
    - base16-bytestring
    - bytestring
    - cryptohash
    - hashable
    - optparse-applicative
    - servant
    - servant-server
    - tar
    - text
    - time
    - unordered-containers
    - uri-encode
    - warp
    - zlib

ghc-options:
    - -Wall
    - -Werror
    - -threaded

executable:
    main: Main.hs
